# Name of the action visible in the action overview
name: Create PR with result of design token export
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    types: token-pr

jobs:
  build:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: mkdir "tokens" directory
        # change tokens here (and in line 32) if you want to use a differently named folder 
        run: 'mkdir -p tokens'
      # this creates a json file from the stringified json from the request body

      - name: create json from request body
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          # it uses the name from your settings that was send as then tokenFileName parameter
          name: 'design-tokens-example.json'
          # it uses the json string that was send as the tokens parameter
          json: ${{ github.event.client_payload.tokens }}
          # it uses the directory named "tokens" to store this json file (change this if you changed it above to use a different folder)
          dir: 'tokens'

      # Make changes to pull request here
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Design Token Update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: design-token-update
          branch-suffix: timestamp
          base: main
          delete-branch: true
          title: "[AUTO] Design Tokens Update"
          body: |
            - Just testing
          assignees: yojenkins
          draft: false
