# Name of the action visible in the action overview
name: Create PR with result of design token export
# this triggers the action when a post to "https://api.github.com/repos/:username/:repo/dispatches" comes in
on:
  repository_dispatch:
    # and the event_type property from the request body is 'update-tokens'
    types: token-pr
# the following defines the jon that is run if the above is true
jobs:
  build:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Make changes to pull request here
      - name: Create Pull Request
        id: createpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Design Token Update
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: design-token-update
          branch-suffix: timestamp
          base: main
          delete-branch: true
          title: "[AUTO] Design Tokens Update"
          body: |
            - Just testing
          assignees: yojenkins
          draft: false
